const multer = require("multer");
const shortId = require("shortid");
const Image = require("../models/Image");

const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, "../../Frontend/src/assets/");
  },
  filename: function (req, file, cb) {
    cb(null, shortId() + file.originalname);
  },
});
const upload = multer({
  storage: storage,
  limits: { fileSize: 4000000 },
}).single("logo");

exports.UploadLogo = async (req, res) => {
  upload(req, res, async function (err) {
    if (err instanceof multer.MulterError) {
      // A Multer error occurred when uploading.
      return res.status(400).json({ error: "File upload error" });
    } else if (err) {
      // An unknown error occurred when uploading.
      console.log(err);
      return res.status(500).json({ error: "Internal server error" });
    }

    // Everything went fine.
    // You can now use req.file to access information about the uploaded file.
    // For example, req.file.filename gives the unique filename generated by multer.
    const logoname = req.file.filename;
    try {
      await Image.create({ logoname });
      res
        .status(200)
        .json({
          message: "File uploaded successfully",
          filename: req.file.filename,
        });
    } catch (err) {
      console.log(err);
    }
    res
      .status(200)
      .json({
        message: "File uploaded successfully",
        filename: req.file.filename,
      });
  });
};
